package cn.gov.jseport.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public BookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andBookidIsNull() {
            addCriterion("bookid is null");
            return (Criteria) this;
        }

        public Criteria andBookidIsNotNull() {
            addCriterion("bookid is not null");
            return (Criteria) this;
        }

        public Criteria andBookidEqualTo(Integer value) {
            addCriterion("bookid =", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotEqualTo(Integer value) {
            addCriterion("bookid <>", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThan(Integer value) {
            addCriterion("bookid >", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookid >=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThan(Integer value) {
            addCriterion("bookid <", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThanOrEqualTo(Integer value) {
            addCriterion("bookid <=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidIn(List<Integer> values) {
            addCriterion("bookid in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotIn(List<Integer> values) {
            addCriterion("bookid not in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidBetween(Integer value1, Integer value2) {
            addCriterion("bookid between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotBetween(Integer value1, Integer value2) {
            addCriterion("bookid not between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNull() {
            addCriterion("business_code is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIsNotNull() {
            addCriterion("business_code is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeEqualTo(String value) {
            addCriterion("business_code =", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotEqualTo(String value) {
            addCriterion("business_code <>", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThan(String value) {
            addCriterion("business_code >", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("business_code >=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThan(String value) {
            addCriterion("business_code <", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLessThanOrEqualTo(String value) {
            addCriterion("business_code <=", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeLike(String value) {
            addCriterion("business_code like", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotLike(String value) {
            addCriterion("business_code not like", value, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeIn(List<String> values) {
            addCriterion("business_code in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotIn(List<String> values) {
            addCriterion("business_code not in", values, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeBetween(String value1, String value2) {
            addCriterion("business_code between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessCodeNotBetween(String value1, String value2) {
            addCriterion("business_code not between", value1, value2, "businessCode");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNull() {
            addCriterion("business_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNotNull() {
            addCriterion("business_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualTo(String value) {
            addCriterion("business_name =", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotEqualTo(String value) {
            addCriterion("business_name <>", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThan(String value) {
            addCriterion("business_name >", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_name >=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThan(String value) {
            addCriterion("business_name <", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("business_name <=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLike(String value) {
            addCriterion("business_name like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotLike(String value) {
            addCriterion("business_name not like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIn(List<String> values) {
            addCriterion("business_name in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotIn(List<String> values) {
            addCriterion("business_name not in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameBetween(String value1, String value2) {
            addCriterion("business_name between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotBetween(String value1, String value2) {
            addCriterion("business_name not between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeIsNull() {
            addCriterion("record_business_code is null");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeIsNotNull() {
            addCriterion("record_business_code is not null");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeEqualTo(String value) {
            addCriterion("record_business_code =", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeNotEqualTo(String value) {
            addCriterion("record_business_code <>", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeGreaterThan(String value) {
            addCriterion("record_business_code >", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("record_business_code >=", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeLessThan(String value) {
            addCriterion("record_business_code <", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeLessThanOrEqualTo(String value) {
            addCriterion("record_business_code <=", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeLike(String value) {
            addCriterion("record_business_code like", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeNotLike(String value) {
            addCriterion("record_business_code not like", value, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeIn(List<String> values) {
            addCriterion("record_business_code in", values, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeNotIn(List<String> values) {
            addCriterion("record_business_code not in", values, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeBetween(String value1, String value2) {
            addCriterion("record_business_code between", value1, value2, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessCodeNotBetween(String value1, String value2) {
            addCriterion("record_business_code not between", value1, value2, "recordBusinessCode");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameIsNull() {
            addCriterion("record_business_name is null");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameIsNotNull() {
            addCriterion("record_business_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameEqualTo(String value) {
            addCriterion("record_business_name =", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameNotEqualTo(String value) {
            addCriterion("record_business_name <>", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameGreaterThan(String value) {
            addCriterion("record_business_name >", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("record_business_name >=", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameLessThan(String value) {
            addCriterion("record_business_name <", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("record_business_name <=", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameLike(String value) {
            addCriterion("record_business_name like", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameNotLike(String value) {
            addCriterion("record_business_name not like", value, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameIn(List<String> values) {
            addCriterion("record_business_name in", values, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameNotIn(List<String> values) {
            addCriterion("record_business_name not in", values, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameBetween(String value1, String value2) {
            addCriterion("record_business_name between", value1, value2, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecordBusinessNameNotBetween(String value1, String value2) {
            addCriterion("record_business_name not between", value1, value2, "recordBusinessName");
            return (Criteria) this;
        }

        public Criteria andRecorderIsNull() {
            addCriterion("recorder is null");
            return (Criteria) this;
        }

        public Criteria andRecorderIsNotNull() {
            addCriterion("recorder is not null");
            return (Criteria) this;
        }

        public Criteria andRecorderEqualTo(String value) {
            addCriterion("recorder =", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotEqualTo(String value) {
            addCriterion("recorder <>", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderGreaterThan(String value) {
            addCriterion("recorder >", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderGreaterThanOrEqualTo(String value) {
            addCriterion("recorder >=", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLessThan(String value) {
            addCriterion("recorder <", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLessThanOrEqualTo(String value) {
            addCriterion("recorder <=", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLike(String value) {
            addCriterion("recorder like", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotLike(String value) {
            addCriterion("recorder not like", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderIn(List<String> values) {
            addCriterion("recorder in", values, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotIn(List<String> values) {
            addCriterion("recorder not in", values, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderBetween(String value1, String value2) {
            addCriterion("recorder between", value1, value2, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotBetween(String value1, String value2) {
            addCriterion("recorder not between", value1, value2, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIsNull() {
            addCriterion("record_time is null");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIsNotNull() {
            addCriterion("record_time is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTimeEqualTo(Date value) {
            addCriterionForJDBCDate("record_time =", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("record_time <>", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("record_time >", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("record_time >=", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeLessThan(Date value) {
            addCriterionForJDBCDate("record_time <", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("record_time <=", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIn(List<Date> values) {
            addCriterionForJDBCDate("record_time in", values, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("record_time not in", values, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("record_time between", value1, value2, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("record_time not between", value1, value2, "recordTime");
            return (Criteria) this;
        }

        public Criteria andStartValidityIsNull() {
            addCriterion("start_validity is null");
            return (Criteria) this;
        }

        public Criteria andStartValidityIsNotNull() {
            addCriterion("start_validity is not null");
            return (Criteria) this;
        }

        public Criteria andStartValidityEqualTo(Date value) {
            addCriterionForJDBCDate("start_validity =", value, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_validity <>", value, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityGreaterThan(Date value) {
            addCriterionForJDBCDate("start_validity >", value, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_validity >=", value, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityLessThan(Date value) {
            addCriterionForJDBCDate("start_validity <", value, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_validity <=", value, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityIn(List<Date> values) {
            addCriterionForJDBCDate("start_validity in", values, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_validity not in", values, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_validity between", value1, value2, "startValidity");
            return (Criteria) this;
        }

        public Criteria andStartValidityNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_validity not between", value1, value2, "startValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityIsNull() {
            addCriterion("end_validity is null");
            return (Criteria) this;
        }

        public Criteria andEndValidityIsNotNull() {
            addCriterion("end_validity is not null");
            return (Criteria) this;
        }

        public Criteria andEndValidityEqualTo(Date value) {
            addCriterionForJDBCDate("end_validity =", value, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_validity <>", value, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityGreaterThan(Date value) {
            addCriterionForJDBCDate("end_validity >", value, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_validity >=", value, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityLessThan(Date value) {
            addCriterionForJDBCDate("end_validity <", value, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_validity <=", value, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityIn(List<Date> values) {
            addCriterionForJDBCDate("end_validity in", values, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityNotIn(List<Date> values) {
            addCriterionForJDBCDate("end_validity not in", values, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_validity between", value1, value2, "endValidity");
            return (Criteria) this;
        }

        public Criteria andEndValidityNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_validity not between", value1, value2, "endValidity");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidIsNull() {
            addCriterion("business_bookid is null");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidIsNotNull() {
            addCriterion("business_bookid is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidEqualTo(Integer value) {
            addCriterion("business_bookid =", value, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidNotEqualTo(Integer value) {
            addCriterion("business_bookid <>", value, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidGreaterThan(Integer value) {
            addCriterion("business_bookid >", value, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_bookid >=", value, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidLessThan(Integer value) {
            addCriterion("business_bookid <", value, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidLessThanOrEqualTo(Integer value) {
            addCriterion("business_bookid <=", value, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidIn(List<Integer> values) {
            addCriterion("business_bookid in", values, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidNotIn(List<Integer> values) {
            addCriterion("business_bookid not in", values, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidBetween(Integer value1, Integer value2) {
            addCriterion("business_bookid between", value1, value2, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBusinessBookidNotBetween(Integer value1, Integer value2) {
            addCriterion("business_bookid not between", value1, value2, "businessBookid");
            return (Criteria) this;
        }

        public Criteria andBookTypeIsNull() {
            addCriterion("book_type is null");
            return (Criteria) this;
        }

        public Criteria andBookTypeIsNotNull() {
            addCriterion("book_type is not null");
            return (Criteria) this;
        }

        public Criteria andBookTypeEqualTo(String value) {
            addCriterion("book_type =", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotEqualTo(String value) {
            addCriterion("book_type <>", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeGreaterThan(String value) {
            addCriterion("book_type >", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeGreaterThanOrEqualTo(String value) {
            addCriterion("book_type >=", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLessThan(String value) {
            addCriterion("book_type <", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLessThanOrEqualTo(String value) {
            addCriterion("book_type <=", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLike(String value) {
            addCriterion("book_type like", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotLike(String value) {
            addCriterion("book_type not like", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeIn(List<String> values) {
            addCriterion("book_type in", values, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotIn(List<String> values) {
            addCriterion("book_type not in", values, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeBetween(String value1, String value2) {
            addCriterion("book_type between", value1, value2, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotBetween(String value1, String value2) {
            addCriterion("book_type not between", value1, value2, "bookType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIsNull() {
            addCriterion("apply_type is null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIsNotNull() {
            addCriterion("apply_type is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeEqualTo(String value) {
            addCriterion("apply_type =", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotEqualTo(String value) {
            addCriterion("apply_type <>", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeGreaterThan(String value) {
            addCriterion("apply_type >", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("apply_type >=", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLessThan(String value) {
            addCriterion("apply_type <", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLessThanOrEqualTo(String value) {
            addCriterion("apply_type <=", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLike(String value) {
            addCriterion("apply_type like", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotLike(String value) {
            addCriterion("apply_type not like", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIn(List<String> values) {
            addCriterion("apply_type in", values, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotIn(List<String> values) {
            addCriterion("apply_type not in", values, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeBetween(String value1, String value2) {
            addCriterion("apply_type between", value1, value2, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotBetween(String value1, String value2) {
            addCriterion("apply_type not between", value1, value2, "applyType");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsIsNull() {
            addCriterion("charge_customs is null");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsIsNotNull() {
            addCriterion("charge_customs is not null");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsEqualTo(String value) {
            addCriterion("charge_customs =", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsNotEqualTo(String value) {
            addCriterion("charge_customs <>", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsGreaterThan(String value) {
            addCriterion("charge_customs >", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsGreaterThanOrEqualTo(String value) {
            addCriterion("charge_customs >=", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsLessThan(String value) {
            addCriterion("charge_customs <", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsLessThanOrEqualTo(String value) {
            addCriterion("charge_customs <=", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsLike(String value) {
            addCriterion("charge_customs like", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsNotLike(String value) {
            addCriterion("charge_customs not like", value, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsIn(List<String> values) {
            addCriterion("charge_customs in", values, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsNotIn(List<String> values) {
            addCriterion("charge_customs not in", values, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsBetween(String value1, String value2) {
            addCriterion("charge_customs between", value1, value2, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andChargeCustomsNotBetween(String value1, String value2) {
            addCriterion("charge_customs not between", value1, value2, "chargeCustoms");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeIsNull() {
            addCriterion("storeroom_code is null");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeIsNotNull() {
            addCriterion("storeroom_code is not null");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeEqualTo(String value) {
            addCriterion("storeroom_code =", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeNotEqualTo(String value) {
            addCriterion("storeroom_code <>", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeGreaterThan(String value) {
            addCriterion("storeroom_code >", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeGreaterThanOrEqualTo(String value) {
            addCriterion("storeroom_code >=", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeLessThan(String value) {
            addCriterion("storeroom_code <", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeLessThanOrEqualTo(String value) {
            addCriterion("storeroom_code <=", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeLike(String value) {
            addCriterion("storeroom_code like", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeNotLike(String value) {
            addCriterion("storeroom_code not like", value, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeIn(List<String> values) {
            addCriterion("storeroom_code in", values, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeNotIn(List<String> values) {
            addCriterion("storeroom_code not in", values, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeBetween(String value1, String value2) {
            addCriterion("storeroom_code between", value1, value2, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomCodeNotBetween(String value1, String value2) {
            addCriterion("storeroom_code not between", value1, value2, "storeroomCode");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameIsNull() {
            addCriterion("storeroom_name is null");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameIsNotNull() {
            addCriterion("storeroom_name is not null");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameEqualTo(String value) {
            addCriterion("storeroom_name =", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameNotEqualTo(String value) {
            addCriterion("storeroom_name <>", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameGreaterThan(String value) {
            addCriterion("storeroom_name >", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameGreaterThanOrEqualTo(String value) {
            addCriterion("storeroom_name >=", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameLessThan(String value) {
            addCriterion("storeroom_name <", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameLessThanOrEqualTo(String value) {
            addCriterion("storeroom_name <=", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameLike(String value) {
            addCriterion("storeroom_name like", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameNotLike(String value) {
            addCriterion("storeroom_name not like", value, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameIn(List<String> values) {
            addCriterion("storeroom_name in", values, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameNotIn(List<String> values) {
            addCriterion("storeroom_name not in", values, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameBetween(String value1, String value2) {
            addCriterion("storeroom_name between", value1, value2, "storeroomName");
            return (Criteria) this;
        }

        public Criteria andStoreroomNameNotBetween(String value1, String value2) {
            addCriterion("storeroom_name not between", value1, value2, "storeroomName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 29 14:48:34 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}