package cn.gov.jseport.entity;

import java.util.ArrayList;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(Integer value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(Integer value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(Integer value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(Integer value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(Integer value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<Integer> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<Integer> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(Integer value1, Integer value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(Integer value1, Integer value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andBookidIsNull() {
            addCriterion("bookid is null");
            return (Criteria) this;
        }

        public Criteria andBookidIsNotNull() {
            addCriterion("bookid is not null");
            return (Criteria) this;
        }

        public Criteria andBookidEqualTo(Integer value) {
            addCriterion("bookid =", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotEqualTo(Integer value) {
            addCriterion("bookid <>", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThan(Integer value) {
            addCriterion("bookid >", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookid >=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThan(Integer value) {
            addCriterion("bookid <", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThanOrEqualTo(Integer value) {
            addCriterion("bookid <=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidIn(List<Integer> values) {
            addCriterion("bookid in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotIn(List<Integer> values) {
            addCriterion("bookid not in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidBetween(Integer value1, Integer value2) {
            addCriterion("bookid between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotBetween(Integer value1, Integer value2) {
            addCriterion("bookid not between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeIsNull() {
            addCriterion("host_business_code is null");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeIsNotNull() {
            addCriterion("host_business_code is not null");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeEqualTo(Integer value) {
            addCriterion("host_business_code =", value, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeNotEqualTo(Integer value) {
            addCriterion("host_business_code <>", value, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeGreaterThan(Integer value) {
            addCriterion("host_business_code >", value, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("host_business_code >=", value, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeLessThan(Integer value) {
            addCriterion("host_business_code <", value, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeLessThanOrEqualTo(Integer value) {
            addCriterion("host_business_code <=", value, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeIn(List<Integer> values) {
            addCriterion("host_business_code in", values, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeNotIn(List<Integer> values) {
            addCriterion("host_business_code not in", values, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeBetween(Integer value1, Integer value2) {
            addCriterion("host_business_code between", value1, value2, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("host_business_code not between", value1, value2, "hostBusinessCode");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameIsNull() {
            addCriterion("host_business_name is null");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameIsNotNull() {
            addCriterion("host_business_name is not null");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameEqualTo(String value) {
            addCriterion("host_business_name =", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameNotEqualTo(String value) {
            addCriterion("host_business_name <>", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameGreaterThan(String value) {
            addCriterion("host_business_name >", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("host_business_name >=", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameLessThan(String value) {
            addCriterion("host_business_name <", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("host_business_name <=", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameLike(String value) {
            addCriterion("host_business_name like", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameNotLike(String value) {
            addCriterion("host_business_name not like", value, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameIn(List<String> values) {
            addCriterion("host_business_name in", values, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameNotIn(List<String> values) {
            addCriterion("host_business_name not in", values, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameBetween(String value1, String value2) {
            addCriterion("host_business_name between", value1, value2, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andHostBusinessNameNotBetween(String value1, String value2) {
            addCriterion("host_business_name not between", value1, value2, "hostBusinessName");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeIsNull() {
            addCriterion("goods_code is null");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeIsNotNull() {
            addCriterion("goods_code is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeEqualTo(Integer value) {
            addCriterion("goods_code =", value, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeNotEqualTo(Integer value) {
            addCriterion("goods_code <>", value, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeGreaterThan(Integer value) {
            addCriterion("goods_code >", value, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_code >=", value, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeLessThan(Integer value) {
            addCriterion("goods_code <", value, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeLessThanOrEqualTo(Integer value) {
            addCriterion("goods_code <=", value, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeIn(List<Integer> values) {
            addCriterion("goods_code in", values, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeNotIn(List<Integer> values) {
            addCriterion("goods_code not in", values, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeBetween(Integer value1, Integer value2) {
            addCriterion("goods_code between", value1, value2, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andGoodsCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_code not between", value1, value2, "goodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeIsNull() {
            addCriterion("host_goods_code is null");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeIsNotNull() {
            addCriterion("host_goods_code is not null");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeEqualTo(Integer value) {
            addCriterion("host_goods_code =", value, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeNotEqualTo(Integer value) {
            addCriterion("host_goods_code <>", value, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeGreaterThan(Integer value) {
            addCriterion("host_goods_code >", value, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("host_goods_code >=", value, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeLessThan(Integer value) {
            addCriterion("host_goods_code <", value, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeLessThanOrEqualTo(Integer value) {
            addCriterion("host_goods_code <=", value, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeIn(List<Integer> values) {
            addCriterion("host_goods_code in", values, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeNotIn(List<Integer> values) {
            addCriterion("host_goods_code not in", values, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeBetween(Integer value1, Integer value2) {
            addCriterion("host_goods_code between", value1, value2, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andHostGoodsCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("host_goods_code not between", value1, value2, "hostGoodsCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeIsNull() {
            addCriterion("wares_code is null");
            return (Criteria) this;
        }

        public Criteria andWaresCodeIsNotNull() {
            addCriterion("wares_code is not null");
            return (Criteria) this;
        }

        public Criteria andWaresCodeEqualTo(Integer value) {
            addCriterion("wares_code =", value, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeNotEqualTo(Integer value) {
            addCriterion("wares_code <>", value, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeGreaterThan(Integer value) {
            addCriterion("wares_code >", value, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("wares_code >=", value, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeLessThan(Integer value) {
            addCriterion("wares_code <", value, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeLessThanOrEqualTo(Integer value) {
            addCriterion("wares_code <=", value, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeIn(List<Integer> values) {
            addCriterion("wares_code in", values, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeNotIn(List<Integer> values) {
            addCriterion("wares_code not in", values, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeBetween(Integer value1, Integer value2) {
            addCriterion("wares_code between", value1, value2, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("wares_code not between", value1, value2, "waresCode");
            return (Criteria) this;
        }

        public Criteria andWaresNameIsNull() {
            addCriterion("wares_name is null");
            return (Criteria) this;
        }

        public Criteria andWaresNameIsNotNull() {
            addCriterion("wares_name is not null");
            return (Criteria) this;
        }

        public Criteria andWaresNameEqualTo(String value) {
            addCriterion("wares_name =", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameNotEqualTo(String value) {
            addCriterion("wares_name <>", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameGreaterThan(String value) {
            addCriterion("wares_name >", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameGreaterThanOrEqualTo(String value) {
            addCriterion("wares_name >=", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameLessThan(String value) {
            addCriterion("wares_name <", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameLessThanOrEqualTo(String value) {
            addCriterion("wares_name <=", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameLike(String value) {
            addCriterion("wares_name like", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameNotLike(String value) {
            addCriterion("wares_name not like", value, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameIn(List<String> values) {
            addCriterion("wares_name in", values, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameNotIn(List<String> values) {
            addCriterion("wares_name not in", values, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameBetween(String value1, String value2) {
            addCriterion("wares_name between", value1, value2, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresNameNotBetween(String value1, String value2) {
            addCriterion("wares_name not between", value1, value2, "waresName");
            return (Criteria) this;
        }

        public Criteria andWaresTypeIsNull() {
            addCriterion("wares_type is null");
            return (Criteria) this;
        }

        public Criteria andWaresTypeIsNotNull() {
            addCriterion("wares_type is not null");
            return (Criteria) this;
        }

        public Criteria andWaresTypeEqualTo(String value) {
            addCriterion("wares_type =", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeNotEqualTo(String value) {
            addCriterion("wares_type <>", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeGreaterThan(String value) {
            addCriterion("wares_type >", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeGreaterThanOrEqualTo(String value) {
            addCriterion("wares_type >=", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeLessThan(String value) {
            addCriterion("wares_type <", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeLessThanOrEqualTo(String value) {
            addCriterion("wares_type <=", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeLike(String value) {
            addCriterion("wares_type like", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeNotLike(String value) {
            addCriterion("wares_type not like", value, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeIn(List<String> values) {
            addCriterion("wares_type in", values, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeNotIn(List<String> values) {
            addCriterion("wares_type not in", values, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeBetween(String value1, String value2) {
            addCriterion("wares_type between", value1, value2, "waresType");
            return (Criteria) this;
        }

        public Criteria andWaresTypeNotBetween(String value1, String value2) {
            addCriterion("wares_type not between", value1, value2, "waresType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNull() {
            addCriterion("goods_type is null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNotNull() {
            addCriterion("goods_type is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeEqualTo(String value) {
            addCriterion("goods_type =", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotEqualTo(String value) {
            addCriterion("goods_type <>", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThan(String value) {
            addCriterion("goods_type >", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("goods_type >=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThan(String value) {
            addCriterion("goods_type <", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThanOrEqualTo(String value) {
            addCriterion("goods_type <=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLike(String value) {
            addCriterion("goods_type like", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotLike(String value) {
            addCriterion("goods_type not like", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIn(List<String> values) {
            addCriterion("goods_type in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotIn(List<String> values) {
            addCriterion("goods_type not in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeBetween(String value1, String value2) {
            addCriterion("goods_type between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotBetween(String value1, String value2) {
            addCriterion("goods_type not between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitInLawIsNull() {
            addCriterion("unit_in_law is null");
            return (Criteria) this;
        }

        public Criteria andUnitInLawIsNotNull() {
            addCriterion("unit_in_law is not null");
            return (Criteria) this;
        }

        public Criteria andUnitInLawEqualTo(String value) {
            addCriterion("unit_in_law =", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawNotEqualTo(String value) {
            addCriterion("unit_in_law <>", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawGreaterThan(String value) {
            addCriterion("unit_in_law >", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawGreaterThanOrEqualTo(String value) {
            addCriterion("unit_in_law >=", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawLessThan(String value) {
            addCriterion("unit_in_law <", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawLessThanOrEqualTo(String value) {
            addCriterion("unit_in_law <=", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawLike(String value) {
            addCriterion("unit_in_law like", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawNotLike(String value) {
            addCriterion("unit_in_law not like", value, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawIn(List<String> values) {
            addCriterion("unit_in_law in", values, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawNotIn(List<String> values) {
            addCriterion("unit_in_law not in", values, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawBetween(String value1, String value2) {
            addCriterion("unit_in_law between", value1, value2, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitInLawNotBetween(String value1, String value2) {
            addCriterion("unit_in_law not between", value1, value2, "unitInLaw");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNull() {
            addCriterion("unit_price is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNotNull() {
            addCriterion("unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceEqualTo(String value) {
            addCriterion("unit_price =", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotEqualTo(String value) {
            addCriterion("unit_price <>", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThan(String value) {
            addCriterion("unit_price >", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThanOrEqualTo(String value) {
            addCriterion("unit_price >=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThan(String value) {
            addCriterion("unit_price <", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThanOrEqualTo(String value) {
            addCriterion("unit_price <=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLike(String value) {
            addCriterion("unit_price like", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotLike(String value) {
            addCriterion("unit_price not like", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIn(List<String> values) {
            addCriterion("unit_price in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotIn(List<String> values) {
            addCriterion("unit_price not in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceBetween(String value1, String value2) {
            addCriterion("unit_price between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotBetween(String value1, String value2) {
            addCriterion("unit_price not between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemIsNull() {
            addCriterion("currency_system is null");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemIsNotNull() {
            addCriterion("currency_system is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemEqualTo(String value) {
            addCriterion("currency_system =", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemNotEqualTo(String value) {
            addCriterion("currency_system <>", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemGreaterThan(String value) {
            addCriterion("currency_system >", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemGreaterThanOrEqualTo(String value) {
            addCriterion("currency_system >=", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemLessThan(String value) {
            addCriterion("currency_system <", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemLessThanOrEqualTo(String value) {
            addCriterion("currency_system <=", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemLike(String value) {
            addCriterion("currency_system like", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemNotLike(String value) {
            addCriterion("currency_system not like", value, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemIn(List<String> values) {
            addCriterion("currency_system in", values, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemNotIn(List<String> values) {
            addCriterion("currency_system not in", values, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemBetween(String value1, String value2) {
            addCriterion("currency_system between", value1, value2, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andCurrencySystemNotBetween(String value1, String value2) {
            addCriterion("currency_system not between", value1, value2, "currencySystem");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 29 14:48:34 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}