package cn.gov.jseport.entity;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gid
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.bookid
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.host_business_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private Integer hostBusinessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.host_business_name
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String hostBusinessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private Integer goodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.host_goods_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private Integer hostGoodsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.wares_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private Integer waresCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.wares_name
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String waresName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.wares_type
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String waresType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit_in_law
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String unitInLaw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit_price
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.currency_system
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String currencySystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gid
     *
     * @return the value of goods.gid
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gid
     *
     * @param gid the value for goods.gid
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.bookid
     *
     * @return the value of goods.bookid
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.bookid
     *
     * @param bookid the value for goods.bookid
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.host_business_code
     *
     * @return the value of goods.host_business_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Integer getHostBusinessCode() {
        return hostBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.host_business_code
     *
     * @param hostBusinessCode the value for goods.host_business_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setHostBusinessCode(Integer hostBusinessCode) {
        this.hostBusinessCode = hostBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.host_business_name
     *
     * @return the value of goods.host_business_name
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getHostBusinessName() {
        return hostBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.host_business_name
     *
     * @param hostBusinessName the value for goods.host_business_name
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setHostBusinessName(String hostBusinessName) {
        this.hostBusinessName = hostBusinessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_code
     *
     * @return the value of goods.goods_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Integer getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_code
     *
     * @param goodsCode the value for goods.goods_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setGoodsCode(Integer goodsCode) {
        this.goodsCode = goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.host_goods_code
     *
     * @return the value of goods.host_goods_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Integer getHostGoodsCode() {
        return hostGoodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.host_goods_code
     *
     * @param hostGoodsCode the value for goods.host_goods_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setHostGoodsCode(Integer hostGoodsCode) {
        this.hostGoodsCode = hostGoodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.wares_code
     *
     * @return the value of goods.wares_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public Integer getWaresCode() {
        return waresCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.wares_code
     *
     * @param waresCode the value for goods.wares_code
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setWaresCode(Integer waresCode) {
        this.waresCode = waresCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.wares_name
     *
     * @return the value of goods.wares_name
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getWaresName() {
        return waresName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.wares_name
     *
     * @param waresName the value for goods.wares_name
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setWaresName(String waresName) {
        this.waresName = waresName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.wares_type
     *
     * @return the value of goods.wares_type
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getWaresType() {
        return waresType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.wares_type
     *
     * @param waresType the value for goods.wares_type
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setWaresType(String waresType) {
        this.waresType = waresType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit
     *
     * @return the value of goods.unit
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit
     *
     * @param unit the value for goods.unit
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit_in_law
     *
     * @return the value of goods.unit_in_law
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getUnitInLaw() {
        return unitInLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit_in_law
     *
     * @param unitInLaw the value for goods.unit_in_law
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setUnitInLaw(String unitInLaw) {
        this.unitInLaw = unitInLaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit_price
     *
     * @return the value of goods.unit_price
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit_price
     *
     * @param unitPrice the value for goods.unit_price
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setUnitPrice(String unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.currency_system
     *
     * @return the value of goods.currency_system
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getCurrencySystem() {
        return currencySystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.currency_system
     *
     * @param currencySystem the value for goods.currency_system
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setCurrencySystem(String currencySystem) {
        this.currencySystem = currencySystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark
     *
     * @return the value of goods.remark
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark
     *
     * @param remark the value for goods.remark
     *
     * @mbggenerated Mon Apr 29 14:48:34 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}